### ISSUE TITLE
 Index out of range when parse data

### ISSUE THREAD

**Issue by sdm5945** [Recouse/EventSource#1]
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range

ServerMessage.swift
<img width="986" alt="image" src="https://github.com/Recouse/EventSource/assets/48941478/40c3187d-bff8-4acb-a28f-e46558796d4f">

**Comment by Recouse** [comment]
I assume this is because the package only supports one newline character. Could you provide some test data to reproduce the error?

**Comment by gdetari** [comment]
Still happening on 0.0.6

**Comment by rhematt** [comment]
Same issue occurs infrequently

**Comment by Recouse** [comment]
I added fix in #7. Could you please test the [message-parser-fix](https://github.com/Recouse/EventSource/tree/message-parser-fix) branch and let me know if it works for you?

**Comment by Recouse** [comment]
This should be fixed with #7. If the error occurs again, feel free to open a new issue.
