### ISSUE TITLE
SSE for watchOS

### ISSUE THREAD

**Issue by jpudysz** [Recouse/EventSource#12]
Hey there! I apologize for bringing up this issue, but there isn’t a discussion tab available in the repository.

I wanted to express my appreciation for your amazing library, which seamlessly integrates SSE with SwiftUI. It’s been working flawlessly on watchOS and I’m thoroughly impressed!

However, I’ve encountered a question. Apple has implemented restrictions on certain types of connections, such as websockets, starting from watchOS 9. Based on my initial testing, it appears that SSE connections are permitted. Everything functions perfectly when I test the application on a real device in debug mode (built from Xcode), as I continuously receive events.

Yet, when I switch to using TestFlight, it seems there is some form of limitation in place, and not all events are being received.

Interestingly, when I connect the watch to a charger, it operates as expected. Could you provide any insights on whether this is the correct approach to utilizing DataStream for watchOS? Have I overlooked something? Thanks!

**Comment by Recouse** [comment]
Hi,
I don't have much experience with watchOS, and haven't tested EventSource on it yet.

Your message suggests the issue might be in how watchOS manages long-lived SSE connections to conserve battery life. I suggest to check Apple's developer documentation on watchOS power management and network requests for guidance.

**Comment by jpudysz** [comment]
Yeah, thanks for the response. After the tests it seems that SSE are not reliable on Apple Watch because of the battery management. Anyway your lib is awesome and I will use it again!
