### ISSUE TITLE
Receiving events without data

### ISSUE THREAD

**Issue by komkovla** [Recouse/EventSource#19]
**Description**

`dataTask` stream would receive event with `event` only without any **data** when data is present. After investigation I found out that `SessionDelegate` would pass only part of data with event, separating response from the server to several `didReceiveData` calls. Sometimes `SessionDelegate` would pass full block, then processing of the message is correct. 

**To Reproduce**

I am communicating with java-spring SSE server on localhost, I can share server with instructions to run it if needed 

Steps:
- Open connection
- Observe event stream
- Receive event
- Received event contain event type but does not contains any data 

**Expected behavior**

Library would cache data to the buffer and parse event only when complete event is received. 

Steps:
- Open connection
- Observe event stream
- Receive event
- Received event contains data 

**Additional context**

 - Platform: iOS 18.1
 - EventSource version: 0.1.1

Thanks for taking your time to implement this library, integration was super easy. I can try to implement caching data myself and create a pull request.

**Comment by komkovla** [comment]
Exactly! I will add example of this issue later

**Comment by komkovla** [comment]
This behaviour is shown in `parseSeparatedMessage` test in 3848ea4ce31bb8a05917827380e8dfa894856bdd

**Comment by Recouse** [comment]
Fixed in #21
