### ISSUE TITLE
trimmingCharacters(in: .whitespaces) should not be used when parsing data.

### ISSUE THREAD

**Issue by Lakr233** [Recouse/EventSource#23]
I'm developing an AI assistant app that make use of your library. Here are a sample of events:

```
event: message
id: 1356ce6b-5504-4f18-8cfb-30c8d6aff925
data: I'm

event: message
id: 1356ce6b-5504-4f18-8cfb-30c8d6aff925
data:  here

event: message
id: 1356ce6b-5504-4f18-8cfb-30c8d6aff925
data:  to

event: message
id: 1356ce6b-5504-4f18-8cfb-30c8d6aff925
data:  assist
```

With that said, extra space before data is removed at ServerEvent.swift:88

This should be reconsidered to remove at most 1 space before data.

**Comment by Recouse** [comment]
Fixed in #24. I will release a new version soon.
